[project]
name = "qtracker-main"
version = "0.1.0"
description = "This project holds the public interface for the Q-Tracker system."
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "numpy>=2.0.2",
    "tensorflow>=2.20.0",
]
